### PR TITLE
Added partial match search filtering

### PR DESCRIPTION
**Pull request by yugensoft**

### CODE REVIEW

**Comment by Xon** [comment]
@yugensoft if I add a filter which matches this just loops forever;

**Comment by yugensoft** [comment]
Strange, doesn't do that on my end; are there any hints why from the console?

**Comment by Xon** [comment]
Nope, just looping & spitting out the chatter of when it loads an entry. Looks like this;
image

Maybe a browser thing? I'm using the latest stable chrome

**Comment by Xon** [comment]
Maybe a difference between whoreplied.js & full/whoreplied.js ?

**Comment by Xon** [comment]
(Note; XF1 can expand js/xenforo/filter_list.js to js/xenforo/full/filter_list.js depending on some settings)

**Comment by yugensoft** [comment]
Ah, it might be something like that, I'll check it's been generated/committed correctly.

**Comment by yugensoft** [comment]
Still can't identify why - the committed min whoreplied.js does contain the `find("li.memberListItem")` same as the full one. Maybe a cache clear is needed?
Edit: does appear to be playing up now `<xen:require js="js/xenforo/filter_list.js" />` is used instead of full, so it is likely something to do with min js stuff.

**Comment by Xon** [comment]
Resyncing the javascript files to my development VM look to have fixed. Ugh. Apologies!

**Comment by Xon** [comment]
But the overlay with the minified filter_list throws a parse error o_O

**Comment by Xon** [comment]
The overlay implementation is glitchy, as it looks like the javascript order isn't being preserved as expected. I think

**Comment by Xon** [comment]
Ok discovered the issue.

**Comment by Xon** [comment]
In XenForo core, `getRequiredExternalsAsHtml()`  does `$typeRequired = array_unique($required[$type]);` while `getRequiredExternals()` does `$typeRequired = array_reverse(array_unique($required[$type]));`

The first is called when XenForo displays as a page, the 2nd for an overlay.

**Comment by Xon** [comment]
Going to call that done

**Comment by yugensoft** [comment]
There's always new ragged edges to discover :)
OK, great

**Pull request merged**
